(global-set-key (kbd "RET") 'newline-and-indent)
(global-set-key "\C-xq" 'comment-or-uncomment-region)
;; (global-set-key (kbd "M-/") 'hippie-expand)
;; (global-set-key (kbd "C-+") 'text-scale-increase)
;; (global-set-key (kbd "C--") 'text-scale-decrease)
;; (global-set-key (kbd "C-c C-k") 'compile)
;; (global-set-key "\C-c\C-d" "\C-a\C- \C-n\M-w\C-y")
;; (global-set-key "\C-cc" "\C-a\C- \C-n\M-w\C-y")
(global-set-key "\C-cg" 'goto-line)
(global-set-key "\C-cF" 'rgrep)
(global-set-key "\C-cf" 'grep)
(global-set-key [f4] 'rename-buffer)
(global-set-key [f3] 'multi-vterm)
;;(global-set-key "\C-cm" 'compile)
(global-set-key "\C-cb" 'comment-box)
;; (global-set-key (kbd "C-s") 'swiper)

(provide  'key_bindings)
